# Generated by Django 4.2.3 on 2023-08-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_commentsmodel_post_videosmodel_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosmodel',
            name='comment',
        ),
        migrations.AddField(
            model_name='videosmodel',
            name='comment',
            field=models.ManyToManyField(null=True, related_name='comments', to='web.commentsmodel'),
        ),
    ]
